name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CI Environment
        uses: ./.github/actions/setup-ci-env
        with:
          setup-node: "true"
          node-version: "20"
          setup-pnpm: "true"
          apt-packages: "build-essential"

      - name: pnpm format:check
        run: pnpm -s format:check

      - name: pnpm lint
        run: pnpm -s lint

      - name: pnpm test
        env:
          CGO_ENABLED: "1"
        run: pnpm -s test

      - name: pnpm build
        env:
          CGO_ENABLED: "1"
        run: pnpm -s build
